// <auto-generated />
using System;
using Inventario.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventario.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("Inventario.Domain.Entities.Bodega", b =>
                {
                    b.Property<int>("BodegaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BodegaID");

                    b.ToTable("Bodegas");
                });

            modelBuilder.Entity("Inventario.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("CategoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoriaID");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Inventario.Domain.Entities.Lote", b =>
                {
                    b.Property<int>("LoteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostoUnitarioLote")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroLote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductoID")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoteID");

                    b.HasIndex("ProductoID", "NumeroLote")
                        .IsUnique();

                    b.ToTable("Lotes");
                });

            modelBuilder.Entity("Inventario.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("ProductoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoSKU")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostoPromedio")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioVenta")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("ProductoID");

                    b.HasIndex("CategoriaID");

                    b.HasIndex("CodigoSKU")
                        .IsUnique();

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Inventario.Domain.Entities.StockBodegaLote", b =>
                {
                    b.Property<int>("StockBodegaLoteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BodegaID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoteID")
                        .HasColumnType("INTEGER");

                    b.HasKey("StockBodegaLoteID");

                    b.HasIndex("LoteID");

                    b.HasIndex("BodegaID", "LoteID")
                        .IsUnique();

                    b.ToTable("StockBodegaLote");
                });

            modelBuilder.Entity("Inventario.Domain.Entities.Lote", b =>
                {
                    b.HasOne("Inventario.Domain.Entities.Producto", "Producto")
                        .WithMany("Lotes")
                        .HasForeignKey("ProductoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Inventario.Domain.Entities.Producto", b =>
                {
                    b.HasOne("Inventario.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Inventario.Domain.Entities.StockBodegaLote", b =>
                {
                    b.HasOne("Inventario.Domain.Entities.Bodega", "Bodega")
                        .WithMany("Stocks")
                        .HasForeignKey("BodegaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventario.Domain.Entities.Lote", "Lote")
                        .WithMany()
                        .HasForeignKey("LoteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bodega");

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("Inventario.Domain.Entities.Bodega", b =>
                {
                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("Inventario.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Inventario.Domain.Entities.Producto", b =>
                {
                    b.Navigation("Lotes");
                });
#pragma warning restore 612, 618
        }
    }
}
